package services

import (
	"strings"
	"time"

	"groupie-backend/models"
)

type ArtistService struct {
	artists  []models.Artist
	concerts []models.Concert
}

func NewArtistService() *ArtistService {
	s := &ArtistService{}
	s.initMockData()
	return s
}

func (s *ArtistService) GetAll() []models.Artist {
	return s.artists
}

func (s *ArtistService) GetByID(id int) (models.Artist, bool) {
	for _, artist := range s.artists {
		if artist.ID == id {
			return artist, true
		}
	}
	return models.Artist{}, false
}

func (s *ArtistService) GetAllConcerts() []models.Concert {
	return s.concerts
}

func (s *ArtistService) SearchConcerts(query string) []models.Concert {
	if query == "" {
		return s.concerts
	}

	var results []models.Concert
	lowerQuery := strings.ToLower(query)

	for _, concert := range s.concerts {
		if strings.Contains(strings.ToLower(concert.Venue), lowerQuery) ||
			strings.Contains(strings.ToLower(concert.City), lowerQuery) ||
			strings.Contains(strings.ToLower(concert.ArtistName), lowerQuery) {
			results = append(results, concert)
		}
	}

	return results
}

func (s *ArtistService) initMockData() {
	s.artists = []models.Artist{
		{
			ID:           1,
			Name:         "Ninho",
			Genre:        "Rap FR",
			Image:        "https://groupie-tracker-assets.s3.eu-north-1.amazonaws.com/artists/1/ninho.jpg.jpg",
			Bio:          "Le recordman du rap français.",
			Members:      []string{"Ninho"},
			CreationDate: 2013,
			FirstAlbum:   "M.I.L.S (2016)",
			Locations:    []string{"Paris, France", "Marseille, France", "Lyon, France"},
			ConcertDates: []string{"12 mai 2026", "18 mai 2026", "25 mai 2026"},
			TopTracks: []models.Track{
				{Title: "Jefe", Plays: "145M", Duration: "3:12"},
				{Title: "Lettre à une femme", Plays: "120M", Duration: "2:58"},
				{Title: "La vie qu'on mène", Plays: "155M", Duration: "3:29"},
				{Title: "Goutte d'eau", Plays: "110M", Duration: "3:02"},
				{Title: "Maman ne le sait pas", Plays: "95M", Duration: "3:22"},
				{Title: "Putana", Plays: "88M", Duration: "3:10"},
				{Title: "Vrai de vrai", Plays: "76M", Duration: "3:05"},
				{Title: "Tout va bien", Plays: "65M", Duration: "3:15"},
			},
			UpcomingDates: []models.ConcertDate{
				{ID: "c1", Venue: "Stade de France", City: "Paris", Date: "12 mai 2026", TicketsURL: "/tickets", Lat: 48.924459, Lng: 2.360164},
				{ID: "c2", Venue: "Vélodrome", City: "Marseille", Date: "18 mai 2026", TicketsURL: "/tickets", Lat: 43.269827, Lng: 5.395887},
				{ID: "c3", Venue: "Groupama Stadium", City: "Lyon", Date: "25 mai 2026", TicketsURL: "/tickets", Lat: 45.765275, Lng: 4.981836},
			},
		},
		{
			ID:           2,
			Name:         "Angèle",
			Genre:        "Pop",
			Image:        "https://groupie-tracker-assets.s3.eu-north-1.amazonaws.com/artists/2/angele.jpg.webp",
			Bio:          "La reine de la pop belge.",
			Members:      []string{"Angèle Van Laeken"},
			CreationDate: 2017,
			FirstAlbum:   "Brol (2018)",
			Locations:    []string{"Bruxelles, Belgique", "Lille, France", "Londres, UK"},
			ConcertDates: []string{"10 juin 2026", "12 juin 2026", "15 juin 2026"},
			TopTracks: []models.Track{
				{Title: "Bruxelles je t'aime", Plays: "95M", Duration: "3:45"},
				{Title: "Balance ton quoi", Plays: "110M", Duration: "3:10"},
				{Title: "Tout oublier", Plays: "180M", Duration: "3:22"},
				{Title: "Oui ou Non", Plays: "85M", Duration: "3:16"},
				{Title: "Ta Reine", Plays: "110M", Duration: "3:33"},
				{Title: "Fever", Plays: "250M", Duration: "2:37"},
				{Title: "Libre", Plays: "70M", Duration: "2:44"},
				{Title: "Flou", Plays: "60M", Duration: "3:19"},
			},
			UpcomingDates: []models.ConcertDate{
				{ID: "c4", Venue: "Forest National", City: "Bruxelles", Date: "10 juin 2026", TicketsURL: "/tickets", Lat: 50.811569, Lng: 4.329868},
				{ID: "c5", Venue: "Zénith", City: "Lille", Date: "12 juin 2026", TicketsURL: "/tickets", Lat: 50.630663, Lng: 3.080772},
				{ID: "c5b", Venue: "O2 Arena", City: "Londres", Date: "15 juin 2026", TicketsURL: "/tickets", Lat: 51.503038, Lng: 0.003154},
			},
		},
		{
			ID:           3,
			Name:         "Gojira",
			Genre:        "Metal",
			Image:        "https://groupie-tracker-assets.s3.eu-north-1.amazonaws.com/artists/3/gojira.jpg",
			Bio:          "La puissance du metal français.",
			Members:      []string{"Joe Duplantier", "Mario Duplantier", "Christian Andreu", "Jean-Michel Labadie"},
			CreationDate: 1996,
			FirstAlbum:   "Terra Incognita (2001)",
			Locations:    []string{"Clisson, France", "Denver, USA", "Tokyo, Japon"},
			ConcertDates: []string{"20 juin 2026", "15 juillet 2026", "2 août 2026"},
			TopTracks: []models.Track{
				{Title: "Stranded", Plays: "80M", Duration: "4:30"},
				{Title: "Silvera", Plays: "70M", Duration: "3:50"},
				{Title: "L'enfant sauvage", Plays: "60M", Duration: "4:17"},
				{Title: "Flying Whales", Plays: "55M", Duration: "7:44"},
				{Title: "Amazonia", Plays: "35M", Duration: "5:00"},
				{Title: "Another World", Plays: "40M", Duration: "4:25"},
				{Title: "The Shooting Star", Plays: "30M", Duration: "5:42"},
				{Title: "Born For One Thing", Plays: "25M", Duration: "4:20"},
			},
			UpcomingDates: []models.ConcertDate{
				{ID: "g1", Venue: "Hellfest", City: "Clisson", Date: "20 juin 2026", TicketsURL: "/tickets", Lat: 47.097193, Lng: -1.271104},
				{ID: "g2", Venue: "Red Rocks", City: "Denver (USA)", Date: "15 juillet 2026", TicketsURL: "/tickets", Lat: 39.665438, Lng: -105.205702},
				{ID: "g3", Venue: "Budokan", City: "Tokyo (Japon)", Date: "2 août 2026", TicketsURL: "/tickets", Lat: 35.693318, Lng: 139.749885},
			},
		},
		{
			ID:           4,
			Name:         "Orelsan",
			Genre:        "Rap FR",
			Image:        "https://groupie-tracker-assets.s3.eu-north-1.amazonaws.com/artists/4/orelsan.jpg",
			Bio:          "Civilisation. La plume la plus aiguisée de Caen.",
			Members:      []string{"Aurélien Cotentin"},
			CreationDate: 2002,
			FirstAlbum:   "Perdu d'avance (2009)",
			Locations:    []string{"Paris, France", "Caen, France", "Bordeaux, France"},
			ConcertDates: []string{"15 novembre 2026", "20 novembre 2026", "25 novembre 2026"},
			TopTracks: []models.Track{
				{Title: "La Quête", Plays: "90M", Duration: "4:00"},
				{Title: "Basique", Plays: "150M", Duration: "3:10"},
				{Title: "L'odeur de l'essence", Plays: "85M", Duration: "4:42"},
				{Title: "Du propre", Plays: "55M", Duration: "3:27"},
				{Title: "San", Plays: "65M", Duration: "4:02"},
				{Title: "La Terre est ronde", Plays: "98M", Duration: "3:39"},
				{Title: "Défaite de famille", Plays: "72M", Duration: "3:44"},
				{Title: "Notes pour trop tard", Plays: "45M", Duration: "7:31"},
			},
			UpcomingDates: []models.ConcertDate{
				{ID: "c6", Venue: "Accor Arena", City: "Paris", Date: "15 novembre 2026", TicketsURL: "/tickets", Lat: 48.838580, Lng: 2.378435},
				{ID: "c7", Venue: "Zénith", City: "Caen", Date: "20 novembre 2026", TicketsURL: "/tickets", Lat: 49.165684, Lng: -0.395156},
				{ID: "c8", Venue: "Arena", City: "Bordeaux", Date: "25 novembre 2026", TicketsURL: "/tickets", Lat: 44.821415, Lng: -0.536979},
			},
		},
		{
			ID:           5,
			Name:         "Daft Punk",
			Genre:        "Electro",
			Image:        "https://groupie-tracker-assets.s3.eu-north-1.amazonaws.com/artists/5/daftpunk.jpg",
			Bio:          "Les légendes. One More Time.",
			Members:      []string{"Thomas Bangalter", "Guy-Manuel de Homem-Christo"},
			CreationDate: 1993,
			FirstAlbum:   "Homework (1997)",
			Locations:    []string{},
			ConcertDates: []string{},
			TopTracks: []models.Track{
				{Title: "One More Time", Plays: "500M", Duration: "5:20"},
				{Title: "Get Lucky", Plays: "1B", Duration: "4:08"},
				{Title: "Harder, Better, Faster, Stronger", Plays: "700M", Duration: "3:45"},
				{Title: "Instant Crush", Plays: "600M", Duration: "5:37"},
				{Title: "Around the World", Plays: "550M", Duration: "7:09"},
				{Title: "Da Funk", Plays: "400M", Duration: "5:28"},
				{Title: "Lose Yourself to Dance", Plays: "350M", Duration: "5:53"},
				{Title: "Technologic", Plays: "300M", Duration: "4:44"},
			},
			UpcomingDates: []models.ConcertDate{},
		},
		{
			ID:           6,
			Name:         "PNL",
			Genre:        "Rap Cloud",
			Image:        "https://groupie-tracker-assets.s3.eu-north-1.amazonaws.com/artists/6/pnl.jpg",
			Bio:          "Deux frères. QLF.",
			Members:      []string{"Ademo", "N.O.S"},
			CreationDate: 2014,
			FirstAlbum:   "Le Monde Chico (2015)",
			Locations:    []string{"Paris, France"},
			ConcertDates: []string{"21 juin 2026"},
			TopTracks: []models.Track{
				{Title: "Au DD", Plays: "300M", Duration: "4:00"},
				{Title: "Da", Plays: "250M", Duration: "3:50"},
				{Title: "Naha", Plays: "200M", Duration: "4:45"},
				{Title: "Onizuka", Plays: "220M", Duration: "4:12"},
				{Title: "Bené", Plays: "180M", Duration: "3:10"},
				{Title: "91's", Plays: "190M", Duration: "3:55"},
				{Title: "Blanka", Plays: "150M", Duration: "4:15"},
				{Title: "A l'ammoniaque", Plays: "170M", Duration: "5:16"},
			},
			UpcomingDates: []models.ConcertDate{
				{ID: "p1", Venue: "Tour Eiffel", City: "Paris", Date: "21 juin 2026", TicketsURL: "/tickets", Lat: 48.858370, Lng: 2.294481},
			},
		},
		{
			ID:           7,
			Name:         "Leto",
			Genre:        "Rap FR",
			Image:        "https://groupie-tracker-assets.s3.eu-north-1.amazonaws.com/artists/7/leto.jpg",
			Bio:          "Le roi de la Trap parisienne.",
			Members:      []string{"Leto"},
			CreationDate: 2016,
			FirstAlbum:   "Trap $tar (2017)",
			Locations:    []string{},
			ConcertDates: []string{},
			TopTracks: []models.Track{
				{Title: "Macaroni", Plays: "80M", Duration: "3:20"},
				{Title: "Tes parents", Plays: "65M", Duration: "3:45"},
				{Title: "Train de vie", Plays: "40M", Duration: "3:10"},
				{Title: "Double Binks", Plays: "55M", Duration: "3:00"},
				{Title: "Paris c'est magique", Plays: "30M", Duration: "3:15"},
				{Title: "Mozart Capitaine Jackson", Plays: "25M", Duration: "2:55"},
				{Title: "Vie de star", Plays: "20M", Duration: "3:05"},
				{Title: "Mélodie", Plays: "18M", Duration: "3:30"},
			},
			UpcomingDates: []models.ConcertDate{},
		},
		{
			ID:           8,
			Name:         "Nono La Grinta",
			Genre:        "Rap FR",
			Image:        "https://groupie-tracker-assets.s3.eu-north-1.amazonaws.com/artists/8/nonolagrinta.jpg",
			Bio:          "La nouvelle pépite du 91.",
			Members:      []string{"Nono La Grinta"},
			CreationDate: 2021,
			FirstAlbum:   "En cours",
			Locations:    []string{},
			ConcertDates: []string{},
			TopTracks: []models.Track{
				{Title: "LA QUOI??", Plays: "15M", Duration: "2:50"},
				{Title: "Paris", Plays: "10M", Duration: "3:00"},
				{Title: "Probleme", Plays: "5M", Duration: "2:45"},
				{Title: "Wari", Plays: "4M", Duration: "3:10"},
				{Title: "Drogue", Plays: "3M", Duration: "2:55"},
				{Title: "Freestyle Grinta #1", Plays: "2M", Duration: "2:30"},
				{Title: "Pas de refrain", Plays: "1.5M", Duration: "2:40"},
				{Title: "Bussdown", Plays: "1M", Duration: "3:05"},
			},
			UpcomingDates: []models.ConcertDate{},
		},
		{
			ID:           9,
			Name:         "Keeqaid",
			Genre:        "Rap FR",
			Image:        "https://groupie-tracker-assets.s3.eu-north-1.amazonaws.com/artists/9/keeqaid.jpg",
			Bio:          "Le futur de la scène.",
			Members:      []string{"Keeqaid"},
			CreationDate: 2020,
			FirstAlbum:   "En cours",
			Locations:    []string{},
			ConcertDates: []string{},
			TopTracks: []models.Track{
				{Title: "Tequila", Plays: "5M", Duration: "2:40"},
				{Title: "Coachella", Plays: "4M", Duration: "3:10"},
				{Title: "Violetta", Plays: "3M", Duration: "2:55"},
				{Title: "Mélodie", Plays: "2.5M", Duration: "3:00"},
				{Title: "Joga Bonito", Plays: "2M", Duration: "2:45"},
				{Title: "Rolex", Plays: "1.5M", Duration: "3:05"},
				{Title: "91", Plays: "1M", Duration: "2:50"},
				{Title: "Freestyle K", Plays: "800k", Duration: "2:30"},
			},
			UpcomingDates: []models.ConcertDate{},
		},
		{
			ID:           10,
			Name:         "Timar",
			Genre:        "Rap FR",
			Image:        "https://groupie-tracker-assets.s3.eu-north-1.amazonaws.com/artists/10/timar.jpg",
			Bio:          "Une voix qui marque.",
			Members:      []string{"Timar"},
			CreationDate: 2019,
			FirstAlbum:   "En cours",
			Locations:    []string{},
			ConcertDates: []string{},
			TopTracks: []models.Track{
				{Title: "Sierra Leone", Plays: "3M", Duration: "2:55"},
				{Title: "4h44", Plays: "2M", Duration: "3:05"},
				{Title: "Rose", Plays: "1.5M", Duration: "2:45"},
				{Title: "100k", Plays: "1M", Duration: "3:10"},
				{Title: "Dans le noir", Plays: "800k", Duration: "3:00"},
				{Title: "Maman", Plays: "700k", Duration: "3:20"},
				{Title: "Zone", Plays: "600k", Duration: "2:50"},
				{Title: "Freestyle T", Plays: "500k", Duration: "2:30"},
			},
			UpcomingDates: []models.ConcertDate{},
		},
		{
			ID:           11,
			Name:         "Lamano",
			Genre:        "Rap FR",
			Image:        "https://groupie-tracker-assets.s3.eu-north-1.amazonaws.com/artists/11/lamano.jpg",
			Bio:          "L'étoile montante.",
			Members:      []string{"Lamano"},
			CreationDate: 2020,
			FirstAlbum:   "En cours",
			Locations:    []string{},
			ConcertDates: []string{},
			TopTracks: []models.Track{
				{Title: "Im sorry", Plays: "8M", Duration: "2:30"},
				{Title: "Canon", Plays: "6M", Duration: "2:45"},
				{Title: "Hiver", Plays: "4M", Duration: "3:00"},
				{Title: "Automne", Plays: "3M", Duration: "2:55"},
				{Title: "Printemps", Plays: "2.5M", Duration: "3:10"},
				{Title: "Eté", Plays: "2M", Duration: "2:40"},
				{Title: "Love", Plays: "1.5M", Duration: "3:05"},
				{Title: "Solo", Plays: "1M", Duration: "2:50"},
			},
			UpcomingDates: []models.ConcertDate{},
		},
		{
			ID:           12,
			Name:         "The Weeknd",
			Genre:        "Pop",
			Image:        "https://groupie-tracker-assets.s3.eu-north-1.amazonaws.com/artists/12/theweeknd.jpg",
			Bio:          "Starboy. L'artiste le plus écouté au monde.",
			Members:      []string{"Abel Tesfaye"},
			CreationDate: 2010,
			FirstAlbum:   "Kiss Land (2013)",
			Locations:    []string{"Los Angeles, USA", "New York, USA", "Londres, UK"},
			ConcertDates: []string{"10 septembre 2026", "15 septembre 2026", "22 septembre 2026"},
			TopTracks: []models.Track{
				{Title: "Blinding Lights", Plays: "3B", Duration: "3:20"},
				{Title: "Starboy", Plays: "2B", Duration: "3:50"},
				{Title: "The Hills", Plays: "1.8B", Duration: "4:02"},
				{Title: "Save Your Tears", Plays: "1.5B", Duration: "3:35"},
				{Title: "Can't Feel My Face", Plays: "1.3B", Duration: "3:33"},
				{Title: "I Feel It Coming", Plays: "1.2B", Duration: "4:29"},
				{Title: "Call Out My Name", Plays: "900M", Duration: "3:48"},
				{Title: "Take My Breath", Plays: "500M", Duration: "3:40"},
			},
			UpcomingDates: []models.ConcertDate{
				{ID: "w1", Venue: "SoFi Stadium", City: "Los Angeles", Date: "10 septembre 2026", TicketsURL: "/tickets", Lat: 33.953463, Lng: -118.339174},
				{ID: "w2", Venue: "MetLife Stadium", City: "New York", Date: "15 septembre 2026", TicketsURL: "/tickets", Lat: 40.812840, Lng: -74.074209},
				{ID: "w3", Venue: "Wembley Stadium", City: "Londres", Date: "22 septembre 2026", TicketsURL: "/tickets", Lat: 51.556025, Lng: -0.279618},
			},
		},
		{
			ID:           13,
			Name:         "Dua Lipa",
			Genre:        "Pop",
			Image:        "https://groupie-tracker-assets.s3.eu-north-1.amazonaws.com/artists/13/dualipa.jpg",
			Bio:          "La reine du Disco Pop moderne.",
			Members:      []string{"Dua Lipa"},
			CreationDate: 2015,
			FirstAlbum:   "Dua Lipa (2017)",
			Locations:    []string{"Barcelone, Espagne", "Milan, Italie"},
			ConcertDates: []string{"10 juillet 2026", "14 juillet 2026"},
			TopTracks: []models.Track{
				{Title: "Levitating", Plays: "1.5B", Duration: "3:23"},
				{Title: "Don't Start Now", Plays: "1.8B", Duration: "3:03"},
				{Title: "New Rules", Plays: "1.6B", Duration: "3:29"},
				{Title: "Physical", Plays: "1.1B", Duration: "3:13"},
				{Title: "Break My Heart", Plays: "1B", Duration: "3:41"},
				{Title: "One Kiss", Plays: "1.3B", Duration: "3:34"},
				{Title: "IDGAF", Plays: "1.2B", Duration: "3:37"},
				{Title: "Love Again", Plays: "800M", Duration: "4:18"},
			},
			UpcomingDates: []models.ConcertDate{
				{ID: "d1", Venue: "Palau Sant Jordi", City: "Barcelone", Date: "10 juillet 2026", TicketsURL: "/tickets", Lat: 41.363385, Lng: 2.152433},
				{ID: "d2", Venue: "Mediolanum Forum", City: "Milan", Date: "14 juillet 2026", TicketsURL: "/tickets", Lat: 45.402283, Lng: 9.145899},
			},
		},
		{
			ID:           14,
			Name:         "Stromae",
			Genre:        "Pop",
			Image:        "https://groupie-tracker-assets.s3.eu-north-1.amazonaws.com/artists/14/stromae.jpg",
			Bio:          "Le maestro belge.",
			Members:      []string{"Paul Van Haver"},
			CreationDate: 2009,
			FirstAlbum:   "Cheese (2010)",
			Locations:    []string{},
			ConcertDates: []string{},
			TopTracks: []models.Track{
				{Title: "Alors on danse", Plays: "900M", Duration: "3:26"},
				{Title: "Papaoutai", Plays: "800M", Duration: "3:52"},
				{Title: "Formidable", Plays: "300M", Duration: "3:33"},
				{Title: "Tous les mêmes", Plays: "250M", Duration: "3:33"},
				{Title: "Santé", Plays: "120M", Duration: "3:11"},
				{Title: "L'enfer", Plays: "180M", Duration: "3:09"},
				{Title: "Carmen", Plays: "150M", Duration: "3:09"},
				{Title: "Ta fête", Plays: "90M", Duration: "2:56"},
			},
			UpcomingDates: []models.ConcertDate{},
		},
		{
			ID:           15,
			Name:         "Aya Nakamura",
			Genre:        "Pop",
			Image:        "https://groupie-tracker-assets.s3.eu-north-1.amazonaws.com/artists/15/nakamura.jpg",
			Bio:          "La reine de France.",
			Members:      []string{"Aya Danioko"},
			CreationDate: 2014,
			FirstAlbum:   "Journal intime (2017)",
			Locations:    []string{},
			ConcertDates: []string{},
			TopTracks: []models.Track{
				{Title: "Djadja", Plays: "850M", Duration: "2:50"},
				{Title: "Pookie", Plays: "600M", Duration: "3:00"},
				{Title: "Copines", Plays: "500M", Duration: "2:51"},
				{Title: "Jolie Nana", Plays: "400M", Duration: "2:27"},
				{Title: "40%", Plays: "300M", Duration: "2:54"},
				{Title: "Comportement", Plays: "350M", Duration: "2:53"},
				{Title: "La Dot", Plays: "250M", Duration: "2:58"},
				{Title: "Sucette", Plays: "200M", Duration: "2:57"},
			},
			UpcomingDates: []models.ConcertDate{},
		},
		{
			ID:           16,
			Name:         "Metallica",
			Genre:        "Metal",
			Image:        "https://groupie-tracker-assets.s3.eu-north-1.amazonaws.com/artists/16/metallica.jpg",
			Bio:          "Les pères fondateurs du thrash metal.",
			Members:      []string{"James Hetfield", "Lars Ulrich", "Kirk Hammett", "Robert Trujillo"},
			CreationDate: 1981,
			FirstAlbum:   "Kill 'Em All (1983)",
			Locations:    []string{},
			ConcertDates: []string{},
			TopTracks: []models.Track{
				{Title: "Enter Sandman", Plays: "1B", Duration: "5:31"},
				{Title: "Master of Puppets", Plays: "900M", Duration: "8:35"},
				{Title: "Nothing Else Matters", Plays: "1.2B", Duration: "6:28"},
				{Title: "One", Plays: "800M", Duration: "7:27"},
				{Title: "The Unforgiven", Plays: "700M", Duration: "6:27"},
				{Title: "For Whom the Bell Tolls", Plays: "600M", Duration: "5:10"},
				{Title: "Fade to Black", Plays: "550M", Duration: "6:57"},
				{Title: "Seek & Destroy", Plays: "500M", Duration: "6:55"},
			},
			UpcomingDates: []models.ConcertDate{},
		},
		{
			ID:           17,
			Name:         "Rammstein",
			Genre:        "Metal",
			Image:        "https://groupie-tracker-assets.s3.eu-north-1.amazonaws.com/artists/17/rammstein.jpg",
			Bio:          "Le Neue Deutsche Härte incarné.",
			Members:      []string{"Till Lindemann", "Richard Kruspe", "Paul Landers", "Oliver Riedel", "Christoph Schneider", "Christian Lorenz"},
			CreationDate: 1994,
			FirstAlbum:   "Herzeleid (1995)",
			Locations:    []string{},
			ConcertDates: []string{},
			TopTracks: []models.Track{
				{Title: "Du Hast", Plays: "800M", Duration: "3:54"},
				{Title: "Sonne", Plays: "600M", Duration: "4:32"},
				{Title: "Ich Will", Plays: "500M", Duration: "3:37"},
				{Title: "Deutschland", Plays: "450M", Duration: "5:23"},
				{Title: "Engel", Plays: "400M", Duration: "4:24"},
				{Title: "Mein Teil", Plays: "350M", Duration: "4:29"},
				{Title: "Feuer Frei!", Plays: "300M", Duration: "3:11"},
				{Title: "Keine Lust", Plays: "280M", Duration: "3:43"},
			},
			UpcomingDates: []models.ConcertDate{},
		},
		{
			ID:           18,
			Name:         "System of a Down",
			Genre:        "Metal",
			Image:        "https://groupie-tracker-assets.s3.eu-north-1.amazonaws.com/artists/18/systemofadown.jpg",
			Bio:          "Metal alternatif politique et explosif.",
			Members:      []string{"Serj Tankian", "Daron Malakian", "Shavo Odadjian", "John Dolmayan"},
			CreationDate: 1994,
			FirstAlbum:   "System of a Down (1998)",
			Locations:    []string{},
			ConcertDates: []string{},
			TopTracks: []models.Track{
				{Title: "Chop Suey!", Plays: "900M", Duration: "3:30"},
				{Title: "Toxicity", Plays: "700M", Duration: "3:39"},
				{Title: "Aerials", Plays: "600M", Duration: "6:11"},
				{Title: "B.Y.O.B.", Plays: "500M", Duration: "4:15"},
				{Title: "Sugar", Plays: "450M", Duration: "2:33"},
				{Title: "Hypnotize", Plays: "400M", Duration: "3:09"},
				{Title: "Lonely Day", Plays: "380M", Duration: "2:48"},
				{Title: "Spiders", Plays: "350M", Duration: "3:35"},
			},
			UpcomingDates: []models.ConcertDate{},
		},
		{
			ID:           19,
			Name:         "DJ Snake",
			Genre:        "Electro",
			Image:        "https://groupie-tracker-assets.s3.eu-north-1.amazonaws.com/artists/19/djsnake.jpg",
			Bio:          "Le DJ français qui a conquis le monde.",
			Members:      []string{"William Grigahcine"},
			CreationDate: 2013,
			FirstAlbum:   "Encore (2016)",
			Locations:    []string{},
			ConcertDates: []string{},
			TopTracks: []models.Track{
				{Title: "Turn Down for What", Plays: "1.2B", Duration: "3:34"},
				{Title: "Taki Taki", Plays: "2.5B", Duration: "3:32"},
				{Title: "Lean On", Plays: "3B", Duration: "2:56"},
				{Title: "Let Me Love You", Plays: "1.8B", Duration: "3:29"},
				{Title: "Magenta Riddim", Plays: "400M", Duration: "2:51"},
				{Title: "Loco Contigo", Plays: "600M", Duration: "2:50"},
				{Title: "Middle", Plays: "900M", Duration: "3:37"},
				{Title: "You Know You Like It", Plays: "500M", Duration: "3:07"},
			},
			UpcomingDates: []models.ConcertDate{},
		},
		{
			ID:           20,
			Name:         "David Guetta",
			Genre:        "Electro",
			Image:        "https://groupie-tracker-assets.s3.eu-north-1.amazonaws.com/artists/20/davidguetta.jpg",
			Bio:          "Le roi de l'EDM mondiale.",
			Members:      []string{"Pierre David Guetta"},
			CreationDate: 1984,
			FirstAlbum:   "Just a Little More Love (2002)",
			Locations:    []string{},
			ConcertDates: []string{},
			TopTracks: []models.Track{
				{Title: "Titanium", Plays: "2B", Duration: "4:05"},
				{Title: "Without You", Plays: "1.5B", Duration: "3:28"},
				{Title: "When Love Takes Over", Plays: "800M", Duration: "3:05"},
				{Title: "Sexy Bitch", Plays: "700M", Duration: "3:15"},
				{Title: "Memories", Plays: "900M", Duration: "3:32"},
				{Title: "Flames", Plays: "600M", Duration: "3:20"},
				{Title: "Hey Mama", Plays: "1.2B", Duration: "3:15"},
				{Title: "Turn Me On", Plays: "500M", Duration: "3:20"},
			},
			UpcomingDates: []models.ConcertDate{},
		},
		{
			ID:           21,
			Name:         "Kavinsky",
			Genre:        "Electro",
			Image:        "https://groupie-tracker-assets.s3.eu-north-1.amazonaws.com/artists/21/kavinsky.jpg",
			Bio:          "L'electro synthwave française.",
			Members:      []string{"Vincent Belorgey"},
			CreationDate: 2005,
			FirstAlbum:   "OutRun (2013)",
			Locations:    []string{},
			ConcertDates: []string{},
			TopTracks: []models.Track{
				{Title: "Nightcall", Plays: "500M", Duration: "4:20"},
				{Title: "Odd Look", Plays: "200M", Duration: "4:14"},
				{Title: "ProtoVision", Plays: "100M", Duration: "4:57"},
				{Title: "Roadgame", Plays: "80M", Duration: "4:19"},
				{Title: "Blizzard", Plays: "60M", Duration: "3:52"},
				{Title: "First Blood", Plays: "50M", Duration: "3:40"},
				{Title: "Pacific Coast Highway", Plays: "40M", Duration: "4:55"},
				{Title: "Testarossa Autodrive", Plays: "35M", Duration: "4:22"},
			},
			UpcomingDates: []models.ConcertDate{},
		},
		{
			ID:           22,
			Name:         "Laylow",
			Genre:        "Rap FR",
			Image:        "https://groupie-tracker-assets.s3.eu-north-1.amazonaws.com/artists/22/laylow.jpg",
			Bio:          "Le Trinity du rap français.",
			Members:      []string{"Jérôme Abela"},
			CreationDate: 2017,
			FirstAlbum:   "Trinity (2020)",
			Locations:    []string{},
			ConcertDates: []string{},
			TopTracks: []models.Track{
				{Title: "TRINITY", Plays: "50M", Duration: "3:25"},
				{Title: "WOOP WOOP", Plays: "40M", Duration: "3:10"},
				{Title: "MEGATRON", Plays: "35M", Duration: "3:30"},
				{Title: "PLUG", Plays: "30M", Duration: "3:15"},
				{Title: "BEST OF", Plays: "25M", Duration: "3:05"},
				{Title: "RAS-LE-BOL", Plays: "22M", Duration: "2:55"},
				{Title: "KUKOČ", Plays: "20M", Duration: "3:20"},
				{Title: "SNOW", Plays: "18M", Duration: "3:40"},
			},
			UpcomingDates: []models.ConcertDate{},
		},
		{
			ID:           23,
			Name:         "Hamza",
			Genre:        "Rap FR",
			Image:        "https://groupie-tracker-assets.s3.eu-north-1.amazonaws.com/artists/23/hamza.jpg",
			Bio:          "Le sauce god belge.",
			Members:      []string{"Hamza Al-Farissi"},
			CreationDate: 2015,
			FirstAlbum:   "Santa Sauce (2018)",
			Locations:    []string{},
			ConcertDates: []string{},
			TopTracks: []models.Track{
				{Title: "HS", Plays: "60M", Duration: "2:45"},
				{Title: "Désolé", Plays: "50M", Duration: "3:00"},
				{Title: "Sincère", Plays: "45M", Duration: "3:15"},
				{Title: "Dale", Plays: "40M", Duration: "2:50"},
				{Title: "Paradise", Plays: "38M", Duration: "3:05"},
				{Title: "1.28", Plays: "35M", Duration: "3:20"},
				{Title: "Santa Sauce", Plays: "32M", Duration: "3:10"},
				{Title: "Mannschaft", Plays: "30M", Duration: "2:55"},
			},
			UpcomingDates: []models.ConcertDate{},
		},
	}

	s.concerts = []models.Concert{
		{
			ID:                1,
			Name:              "Ninho - Stade de France",
			ArtistID:          1,
			ArtistName:        "Ninho",
			Venue:             "Stade de France",
			City:              "Paris",
			Date:              time.Date(2026, 5, 12, 20, 0, 0, 0, time.UTC),
			ImageURL:          "https://groupie-tracker-assets.s3.eu-north-1.amazonaws.com/artists/1/ninho.jpg.jpg",
			StandardPrice:     79.99,
			VIPPrice:          189.99,
			AvailableStandard: 250,
			AvailableVIP:      100,
			CreatedAt:         time.Now(),
		},
		{
			ID:                2,
			Name:              "Ninho - Vélodrome",
			ArtistID:          1,
			ArtistName:        "Ninho",
			Venue:             "Vélodrome",
			City:              "Marseille",
			Date:              time.Date(2026, 5, 18, 20, 0, 0, 0, time.UTC),
			ImageURL:          "https://groupie-tracker-assets.s3.eu-north-1.amazonaws.com/artists/1/ninho.jpg.jpg",
			StandardPrice:     79.99,
			VIPPrice:          189.99,
			AvailableStandard: 200,
			AvailableVIP:      80,
			CreatedAt:         time.Now(),
		},
		{
			ID:                3,
			Name:              "Angèle - Forest National",
			ArtistID:          2,
			ArtistName:        "Angèle",
			Venue:             "Forest National",
			City:              "Bruxelles",
			Date:              time.Date(2026, 6, 10, 20, 0, 0, 0, time.UTC),
			ImageURL:          "https://groupie-tracker-assets.s3.eu-north-1.amazonaws.com/artists/2/angele.jpg.webp",
			StandardPrice:     69.99,
			VIPPrice:          159.99,
			AvailableStandard: 180,
			AvailableVIP:      70,
			CreatedAt:         time.Now(),
		},
		{
			ID:                4,
			Name:              "Gojira - Hellfest",
			ArtistID:          3,
			ArtistName:        "Gojira",
			Venue:             "Hellfest",
			City:              "Clisson",
			Date:              time.Date(2026, 6, 20, 18, 0, 0, 0, time.UTC),
			ImageURL:          "https://groupie-tracker-assets.s3.eu-north-1.amazonaws.com/artists/3/gojira.jpg",
			StandardPrice:     89.99,
			VIPPrice:          199.99,
			AvailableStandard: 300,
			AvailableVIP:      120,
			CreatedAt:         time.Now(),
		},
		{
			ID:                5,
			Name:              "Orelsan - Accor Arena",
			ArtistID:          4,
			ArtistName:        "Orelsan",
			Venue:             "Accor Arena",
			City:              "Paris",
			Date:              time.Date(2026, 11, 15, 20, 0, 0, 0, time.UTC),
			ImageURL:          "https://groupie-tracker-assets.s3.eu-north-1.amazonaws.com/artists/4/orelsan.jpg",
			StandardPrice:     75.00,
			VIPPrice:          175.00,
			AvailableStandard: 220,
			AvailableVIP:      90,
			CreatedAt:         time.Now(),
		},
		{
			ID:                6,
			Name:              "PNL - Tour Eiffel",
			ArtistID:          6,
			ArtistName:        "PNL",
			Venue:             "Tour Eiffel",
			City:              "Paris",
			Date:              time.Date(2026, 6, 21, 21, 0, 0, 0, time.UTC),
			ImageURL:          "https://groupie-tracker-assets.s3.eu-north-1.amazonaws.com/artists/6/pnl.jpg",
			StandardPrice:     0.00,
			VIPPrice:          0.00,
			AvailableStandard: 0,
			AvailableVIP:      0,
			CreatedAt:         time.Now(),
		},
		{
			ID:                7,
			Name:              "The Weeknd - SoFi Stadium",
			ArtistID:          12,
			ArtistName:        "The Weeknd",
			Venue:             "SoFi Stadium",
			City:              "Los Angeles",
			Date:              time.Date(2026, 9, 10, 20, 0, 0, 0, time.UTC),
			ImageURL:          "https://groupie-tracker-assets.s3.eu-north-1.amazonaws.com/artists/12/theweeknd.jpg",
			StandardPrice:     129.99,
			VIPPrice:          299.99,
			AvailableStandard: 350,
			AvailableVIP:      150,
			CreatedAt:         time.Now(),
		},
		{
			ID:                8,
			Name:              "Dua Lipa - Palau Sant Jordi",
			ArtistID:          13,
			ArtistName:        "Dua Lipa",
			Venue:             "Palau Sant Jordi",
			City:              "Barcelone",
			Date:              time.Date(2026, 7, 10, 21, 0, 0, 0, time.UTC),
			ImageURL:          "https://groupie-tracker-assets.s3.eu-north-1.amazonaws.com/artists/13/dualipa.jpg",
			StandardPrice:     99.99,
			VIPPrice:          229.99,
			AvailableStandard: 180,
			AvailableVIP:      80,
			CreatedAt:         time.Now(),
		},
	}
}
